### ISSUE TITLE
How to decrease the gap between ticker sections .

### ISSUE THREAD

**Issue by neodavids** [TuomoKu/SPX-GC#23]
When scrolling the ticker ( ticker sheet html template) how do I make the text flow continuously? There is a very big delay and blank period on air when switching from news section to another section.
I need help @TuomoKu .
Thanks!

**Comment by TuomoKu** [comment]
Hey,
the demo ticker was done this way by design. A continuously running ticker would need to be created separately and the demo one may not be an ideal starting point for it. I will add this as an idea to the wish-list though...

There are javascript libraries and demos of nonstop tickers online and should be relatively easy to combine the Sheet capabilities of the demo template and a non-stop ticker from some other source. I would encourage to look into those. 

And if you happen to develop one and would like to share it please let me know 👍
